INSERT INTO public.book(id, title, author, genre, publisher) VALUES (1,'Age of Discontuinity The','Drucker Peter','economics','Random House');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (2,'Age of Wrath The','Eraly Abraham','history','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (3,'Aghal Paghal','Deshpande P L','nonfiction','Mauj');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (4,'Ahe Manohar Tari','Deshpande Sunita','nonfiction','Mauj');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (5,'All the Presidents Men','Woodward Bob','history','Random House');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (6,'Amulet of Samarkand The','Stroud Jonathan','fiction','Random House');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (7,'Analysis Vol I','Tao Terence','mathematics','HBA');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (8,'Angels & Demons','Brown Dan','fiction','Random House');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (9,'Argumentative Indian The','Sen Amartya','nonfiction','Picador');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (10,'Artist and the Mathematician The','Aczel Amir','science','HighStakes');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (11,'Asami Asami','Deshpande P L','fiction','Mauj');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (12,'Ashenden of The British Agent','Maugham William S','fiction','Vintage');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (13,'Beautiful and the Damned The','Deb Siddhartha','nonfiction','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (14,'Beyond the Three Seas','Dalrymple William','history','Random House');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (15,'Birth of a Theorem','Villani Cedric','mathematics','Bodley Head');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (16,'Bookless in Baghdad','Tharoor Shashi','nonfiction','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (17,'Brethren The','Grisham John','fiction','Random House');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (18,'Burning Bright','Steinbeck John','fiction','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (19,'Catch 22','Heller Joseph','fiction','Random House');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (20,'City of Joy The','Lapierre Dominique','fiction','vikas');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (21,'Clash of Civilizations and Remaking of the World Order','Huntington Samuel','history','Simon&Schuster');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (22,'Complete Mastermind The','BBC','nonfiction','BBC');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (23,'Complete Sherlock Holmes The - Vol I','Doyle Arthur Conan','fiction','Random House');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (24,'Complete Sherlock Holmes The - Vol II','Doyle Arthur Conan','fiction','Random House');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (25,'Computer Vision A Modern Approach','Forsyth David','data_science','Pearson');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (26,'Crime and Punishment','Dostoevsky Fyodor','fiction','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (27,'Data Mining Handbook','Nisbet Robert','data_science','Apress');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (28,'Data Scientists at Work','Sebastian Gutierrez','data_science','Apress');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (29,'Data Smart','Foreman John','data_science','Wiley');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (30,'Data Structures Using C & C++','Tanenbaum Andrew','computer_science','Prentice Hall');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (31,'Doctor in the Nude','Gordon Richard','fiction','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (32,'Down and Out in Paris & London','Orwell George','nonfiction','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (33,'Drunkards Walk The','Mlodinow Leonard','science','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (34,'Dylan on Dylan','Dylan Bob','nonfiction','Random House');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (35,'Econometric Analysis','Greene W. H.','economics','Pearson');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (36,'Electric Universe','Bodanis David','science','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (37,'False Impressions','Archer Jeffery','fiction','Pan');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (38,'Farewell to Arms A','Hemingway Ernest','fiction','Rupa');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (39,'Freakonomics','Dubner Stephen','economics','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (40,'Free Will','Harris Sam','philosophy','FreePress');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (41,'Freedom at Midnight','Lapierre Dominique','history','vikas');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (42,'Fundamentals of Wavelets','Goswami Jaideva','signal_processing','Wiley');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (43,'God Created the Integers','Hawking Stephen','mathematics','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (44,'Great Indian Novel The','Tharoor Shashi','fiction','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (45,'Great War for Civilization The','Fisk Robert','history','HarperCollins');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (46,'Gun Gayin Awadi','Deshpande P L','nonfiction','Mauj');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (47,'Hidden Connections The','Capra Fritjof','science','HarperCollins');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (48,'History of Western Philosophy','Russell Bertrand','philosophy','Routledge');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (49,'How to Think Like Sherlock Holmes','Konnikova Maria','psychology','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (50,'Hunchback of Notre Dame The','Hugo Victor','fiction','Random House');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (51,'Idea of Justice The','Sen Amartya','nonfiction','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (52,'Identity & Violence','Sen Amartya','philosophy','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (53,'Image Processing & Mathematical Morphology','Shih Frank','signal_processing','CRC');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (54,'In a Free State','Naipaul V. S.','fiction','Rupa');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (55,'India from Midnight to Milennium','Tharoor Shashi','history','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (56,'Integration of the Indian States','Menon V P','history','Orient Blackswan');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (57,'Introduction to Algorithms','Cormen Thomas','computer_science','MIT Press');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (58,'Journal of a Novel','Steinbeck John','fiction','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (59,'Jurassic Park','Crichton Michael','fiction','Random House');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (60,'Last Lecture The','Pausch Randy','nonfiction','Hyperion');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (61,'Last Mughal The','Dalrymple William','history','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (62,'Learning OpenCV','Bradsky Gary','data_science','OReilly');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (63,'Let Us C','Kanetkar Yashwant','computer_science','Prentice Hall');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (64,'Machine Learning for Hackers','Conway Drew','data_science','OReilly');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (65,'Making Software','Oram Andy','computer_science','OReilly');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (66,'Manasa','Kale V P','nonfiction','Mauj');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (67,'Maqta-e-Ghalib','Garg Sanjay','fiction','Mauj');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (68,'Maughams Collected Short Stories Vol 3','Maugham William S','fiction','Vintage');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (69,'Moon is Down The','Steinbeck John','fiction','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (70,'Nature of Statistical Learning Theory The','Vapnik Vladimir','data_science','Springer');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (71,'New Machiavelli The','Wells H. G.','fiction','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (72,'New Markets & Other Essays','Drucker Peter','economics','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (73,'O Jerusalem!','Lapierre Dominique','history','vikas');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (74,'On Education','Russell Bertrand','philosophy','Routledge');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (75,'Once There Was a War','Steinbeck John','nonfiction','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (76,'One','Bach Richard','nonfiction','Dell');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (77,'Orientalism','Said Edward','history','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (78,'Outsider The','Camus Albert','fiction','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (79,'Physics & Philosophy','Heisenberg Werner','science','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (80,'Pillars of the Earth The','Follett Ken','fiction','Random House');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (81,'Principles of Communication Systems','Taub Schilling','computer_science','TMH');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (82,'Prisoner of Birth A','Archer Jeffery','fiction','Pan');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (83,'Python for Data Analysis','McKinney Wes','data_science','OReilly');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (84,'Radiowaril Bhashane & Shrutika','Deshpande P L','nonfiction','Mauj');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (85,'Raisin in the Sun A','Hansberry Lorraine','fiction','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (86,'Rationality & Freedom','Sen Amartya','economics','Springer');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (87,'Return of the Primitive','Rand Ayn','philosophy','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (88,'Russian Journal A','Steinbeck John','nonfiction','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (89,'Scoop!','Nayar Kuldip','history','HarperCollins');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (90,'Sea of Poppies','Ghosh Amitav','fiction','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (91,'Signal and the Noise The','Silver Nate','data_science','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (92,'Slaughterhouse Five','Vonnegut Kurt','fiction','Random House');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (93,'Social Choice & Welfare Vol 39 No. 1','Various','economics','Springer');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (94,'Soft Computing & Intelligent Systems','Gupta Madan','data_science','Elsevier');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (95,'Statistical Decision Theory','Pratt John','data_science','MIT Press');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (96,'Story of Philosophy The','Durant Will','philosophy','Pocket');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (97,'Structure & Interpretation of Computer Programs','Sussman Gerald','computer_science','MIT Press');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (98,'Superfreakonomics','Dubner Stephen','economics','HarperCollins');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (99,'Surely Youre Joking Mr Feynman','Feynman Richard','science','Random House');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (100,'Tales of Mystery and Imagination','Poe Edgar Allen','fiction','HarperCollins');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (101,'Tao of Physics The','Capra Fritjof','science','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (102,'Textbook of Economic Theory','Stonier Alfred','economics','Pearson');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (103,'Theory of Everything The','Hawking Stephen','science','Jaico');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (104,'To Sir With Love','Braithwaite','fiction','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (105,'Trial The','Kafka Frank','fiction','Random House');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (106,'Uncommon Wisdom','Capra Fritjof','nonfiction','Fontana');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (107,'Veteran The','Forsyth Frederick','fiction','Transworld');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (108,'We the Living','Rand Ayn','fiction','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (109,'Wealth of Nations The','Smith Adam','economics','Random House');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (110,'Winter of Our Discontent The','Steinbeck John','fiction','Penguin');
INSERT INTO public.book(id, title, author, genre, publisher) VALUES (111,'Zen & The Art of Motorcycle Maintenance','Pirsig Robert','philosophy','Vintage');